name: flutter_injected_web3
description: A web3 injection library for flutter.
version: 1.0.1
homepage: https://github.com/tct68/flutter_injected_web3

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter_inappwebview: ^6.0.0
  flutter:
    sdk: flutter
  flutter_inappwebview_android: ^1.0.13
dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0

flutter:
  uses-material-design: true
  assets:
    - packages/flutter_injected_web3/assets/provider.min.js
